version: 2.1
orbs:
  docker: circleci/docker@0.5.19
  django-tools: pennlabs/django-tools@0.0.2
  helm-tools: pennlabs/helm-tools@0.1.7

branch-filters: &branch-filters
  filters:
    branches:
      only:
        - master
jobs:
  lint:
    working_directory: ~/pennlabs
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node-modules
      - run:
          name: Lint
          command: |
            yarn lint

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - lint
      - docker/publish:
          name: publish-site
          requires:
            - lint
          cache_from: 'pennlabs/website'
          image: 'pennlabs/website'
          tag: '${CIRCLE_SHA1},latest'
          context: docker-publish
          extra_build_args: '--build-arg GHOST_API_KEY=$GHOST_API_KEY'
          <<: *branch-filters
      - helm-tools/deploy:
          requires:
            - publish-site
          context: k8s-deploy
          <<: *branch-filters
